export default {
  STATES_GET_REQUEST: "USER_GET_REQUEST",
  STATES_GET_RECEIVE: "USER_GET_SUCCESS",
  STATES_GET_ERROR: "USER_GET_ERROR",
  STATES_CLEAR: "USER_CLEAR",
  STATES_CLEAR_ERROR: "USER_CLEAR_ERROR"
};
